language: node_js
node_js:
    - 12
before_deploy:
    - tsc
after_success:
    - cd dist && npm pack
deploy:
    provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_API_TOKEN"
    skip_cleanup: true
    on:
        branch: main